test(workflow): update mac/linux/win tests

diff --git a/.github/workflows/mac-tests.yml b/.github/workflows/mac-tests.yml
--- a/.github/workflows/mac-tests.yml
+++ b/.github/workflows/mac-tests.yml
@@ -1,4 +1,5 @@
-name: MacOS tests
+---
+name: Mac Tests
 
 on:
     push:
@@ -8,9 +9,12 @@ on:
 
 jobs:
     build:
+        name: Test Program on MacOS
         runs-on: macos-latest
+
         steps:
-            - uses: actions/checkout@v7
+            - name: Check out code from GitHub
+              uses: actions/checkout@v7
 
             - name: Set up Python
               uses: actions/setup-python@v7
@@ -19,15 +23,38 @@ jobs:
 
             - name: Install dependencies
               run: |
-                  python -m pip install --upgrade pip
-                  pip install -r requirements.txt
+                  python3 -m pip install --upgrade pip
+                  pip3 install -r requirements.txt
+
             - name: Build Executable
               run: |
-                  chmod +x build-mac.sh
-                  ./build-mac.sh
+                  chmod +x ./build-scripts/build-mac.sh
+                  ./build-scripts/build-mac.sh
+                  tree -af
 
-            - name: Archive Executable
+            - name: Verify build outputs
+              run: |
+                  expected=(
+                      "scr/webhook-manager"
+                  )
+
+                  for file in "${expected[@]}"; do
+                      if [[ ! -f "$file" ]]; then
+                          echo "::error::Build output missing: $file"
+                          exit 1
+                      else
+                          echo "OK: $file"
+                      fi
+                  done
+
+            - name: Compute Commit SHA
+              id: vars
+              run: |
+                  echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
+
+            - name: Archive artifact
               uses: actions/upload-artifact@v7
               with:
-                  name: webhook-controller-mac
-                  path: scr/webhook-controller
+                  name: webhook-manager-mac_${{ steps.vars.outputs.sha_short }}
+                  path: |
+                      scr/webhook-manager
diff --git a/.github/workflows/win-tests.yml b/.github/workflows/win-tests.yml
--- a/.github/workflows/win-tests.yml
+++ b/.github/workflows/win-tests.yml
@@ -1,4 +1,5 @@
-name: Windows tests
+---
+name: Win Tests
 
 on:
     push:
@@ -8,9 +9,12 @@ on:
 
 jobs:
     build:
+        name: Test Program on Windows
         runs-on: windows-latest
+
         steps:
-            - uses: actions/checkout@v7
+            - name: Check out code from GitHub
+              uses: actions/checkout@v7
 
             - name: Set up Python
               uses: actions/setup-python@v7
@@ -18,16 +22,41 @@ jobs:
                   python-version: "3.14"
 
             - name: Install dependencies
+              shell: bash
               run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt
 
             - name: Build Executable
+              shell: bash
               run: |
-                  .\build-win.cmd
+                  ./build-scripts/build-win.cmd
+                  tree -fa
 
-            - name: Archive Executable
+            - name: Verify build outputs
+              shell: bash
+              run: |
+                  expected=(
+                      "scr/webhook-manager"
+                  )
+
+                  for file in "${expected[@]}"; do
+                      if [[ ! -f "$file" ]]; then
+                          echo "::error::Build output missing: $file"
+                          exit 1
+                      else
+                          echo "OK: $file"
+                      fi
+                  done
+
+            - name: Compute Commit SHA
+              id: vars
+              run: |
+                  echo "sha_short=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
+
+            - name: Archive artifact
               uses: actions/upload-artifact@v7
               with:
-                  name: webhook-controller-win
-                  path: scr\webhook-controller.exe
+                  name: webhook-manager-win_${{ steps.vars.outputs.sha_short }}
+                  path: |
+                      scr/webhook-manager
